easy_admin:
    entities:
        # List the entity class name you want to manage
        piscine:
            list:
                actions: ['start', 'stop']
            class: App\Entity\Piscine
        user:
            class: App\Entity\User
        mesure:
            class: App\Entity\Mesure
        program:
            class: App\Entity\Programme
        programSelection:
            class: App\Entity\ProgramSelection
